DROP DATABASE IF EXISTS employeeDataBase;
CREATE DATABASE employeeDataBase;
USE employeeDataBase;

CREATE TABLE role (
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR NOT NULL,
salary DECIMAL NOT NULL,
PRIMARY KEY ()
);

CREATE TABLE department (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(35) NOT NULL,
PRIMARY KEY(id)
);
